# Generated by Django 2.0.4 on 2018-11-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bicicleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('marca', models.CharField(blank=True, max_length=45)),
                ('modelo', models.CharField(blank=True, max_length=45)),
                ('categoria', models.CharField(choices=[('MONT', 'Montaña'), ('URB', 'Urbana'), ('RU', 'Ruta')], max_length=45)),
                ('imagen', models.ImageField(upload_to='imagenes_bicicletas')),
                ('aro', models.IntegerField()),
                ('talla', models.FloatField()),
                ('color', models.CharField(blank=True, max_length=45)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
