# Generated by Django 2.1.3 on 2018-11-15 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_catalogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='bicicleta',
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogo'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='categoria',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='categoria',
            field=models.CharField(blank=True, choices=[('MONT', 'Montaña'), ('URB', 'Urbana'), ('RU', 'Ruta')], max_length=45),
        ),
    ]
