# Generated by Django 2.1.3 on 2018-11-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20181115_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='codigo',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='codigo',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
