# Generated by Django 2.1.3 on 2018-11-15 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20181115_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='aro',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='catalogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogo'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='categoria',
            field=models.CharField(choices=[('MONT', 'Montaña'), ('URB', 'Urbana'), ('RU', 'Ruta')], max_length=45),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='codigo',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='color',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes_bicicletas'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='marca',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='modelo',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='categoria',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='codigo',
            field=models.CharField(max_length=45),
        ),
    ]
