# Generated by Django 2.1.3 on 2018-11-15 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20181115_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('precio', models.IntegerField()),
                ('catalogo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogo')),
            ],
        ),
    ]
