# Generated by Django 2.1.3 on 2018-11-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_equipamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='categoria',
            field=models.CharField(choices=[('MONT', 'Montaña'), ('URB', 'Urbana'), ('RU', 'Ruta'), ('EQUIP', 'Equipamiento')], max_length=45),
        ),
    ]
