# Generated by Django 2.1.3 on 2018-11-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20181115_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogo',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
