# Generated by Django 2.0.4 on 2018-11-16 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_auto_20181115_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogo',
            old_name='categorias',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='codigo',
        ),
    ]
